### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by shveik** [IBM-Bluemix-Docs/containers#1110]
Under "Privately expose apps using a custom domain with TLS", step 6, looks like the formatting is off around "network traffic cannot be forwarded"

**Comment by Rachael-Graham** [comment]
@shveik Thanks for the catch! Change in progress.

**Comment by Rachael-Graham** [comment]
Changes are live in prod: https://console.bluemix.net/docs/containers/cs_ingress.html#private_ingress_tls
