### ISSUE TITLE
On the main diagram the numbering is out of sync with the list below

### ISSUE THREAD

**Issue by mjperrins** [IBM-Bluemix-Docs/containers#1362]
On the main diagram the numbering is out of sync

<img width="791" alt="screen shot 2018-02-17 at 2 03 43 pm" src="https://user-images.githubusercontent.com/16599999/36345172-958edf40-13eb-11e8-8416-58479c993ec2.png">

(1) the simple option is not described in the numbered list below the diagram and the descriptions map to 2,3,4,5

**Comment by smguilia** [comment]
Updated diagram can be found here: https://console.bluemix.net/docs/containers/cs_app.html#app
