### ISSUE TITLE
command typo?

### ISSUE THREAD

**Issue by jesusmah** [IBM-Bluemix-Docs/containers#1566]
I was reading through the following piece of documentation:

https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_ingress.md#enabling-the-default-private-application-load-balancer

when I realised there are a couple of commands where `bx cs` is duplicate. That is, the command appears as `bx cs bx cs ....` is that correct?

Thanks

**Comment by Nadine2016** [comment]
@jesusmah thanks for catching this error. The command should be `bx cs ...` and not `bx cs bx cs`. We already updated the docs, the fix will be pushed to prod today. 

Thanks

**Comment by Nadine2016** [comment]
Code is merged. fix will be in prod in a few hours. closing.
