### ISSUE TITLE
Cert Manager - spelt wrongly in the picture.

### ISSUE THREAD

**Issue by sreek-iyer** [IBM-Bluemix-Docs/containers#2222]
https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_secure.md

In this document, and in the picture under section cluster trust, the  cloud certificate manager spelling is incorrect. ( manageger)

**Comment by artberger** [comment]
Thanks for your feedback! I've revised the spelling & image, and it will go out with our next prod push. I'm going to close this issue here.

**Comment by sreek-iyer** [comment]
thank you
