### ISSUE TITLE
Instructions for creating CR tokens are outdated?

### ISSUE THREAD

**Issue by cin** [IBM-Bluemix-Docs/containers#2226]
I could be doing something wrong, but it appears the instructions for how to create container registry tokens are outdated. They can be found [here](https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_dedicated_tokens.md).

Assuming you've setup `bx` and the `cr` plugin, It appears that steps 1-4 can be reduced to:
`bx cr token-add --description "description text" --non-expiring -q`

**Comment by Rachael-Graham** [comment]
Thanks @cin for bringing this to my attention! Those steps were for our old Kraken setup. I've updated them to include the simpler command you proposed: https://console.bluemix.net/docs/containers/cs_dedicated_tokens.html#cs_dedicated_tokens

Closing; reopen if needed!
