### ISSUE TITLE
ic: command not found

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix-Docs/containers#2234]
https://console.bluemix.net/docs/containers/cs_integrations.html#adding_resource_cluster

Change `ic` to `ibmcloud`

**Comment by rvennam** [comment]
I see that `ic` is now an alias on the latest CLI. However, I still think this can be confusing to the user when the docs switch between `ibmcloud` and `ic`.

**Comment by rvennam** [comment]
Closing issue - ideally, all documentation remains consistent using ic or ibmcloud

**Comment by lekhasy** [comment]
I got the same error from this doc:
https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-logdna_agent_image
Please make the naming consistent.
