### ISSUE TITLE
Possible wrong description for instruction

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Bluemix-Docs/containers#2262]
In https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_annotations.md#tcp-ports-for-application-load-balancers-tcp-ports under point 6 of the instructions it reads `Update your ALB configuration.` but the operation actually creates the Ingress service.

**Comment by Rachael-Graham** [comment]
Hi there-- `kubectl apply` can be used to create, but can also be used update a file. For reference, see: https://kubernetes.io/docs/reference/kubectl/conventions/#kubectl-apply Closing but reopen with further questions!

**Comment by bennythejudge** [comment]
Hi, I am not referring to the command. I refer to the description of the command.
It looks to me like that is creating the Ingress service which is not the same thing as "updating the ALB".
I could be wrong.

**Comment by Rachael-Graham** [comment]
Ah, I see what you are saying now. I am making this assumption that users already have an Ingress config file, and are updating the file after they have added the annotation. But this might not be the case. I will change to "create or update"
