### ISSUE TITLE
Is the example fitting for the instructions?

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Bluemix-Docs/containers#2263]
In https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_annotations.md#tcp-ports-for-application-load-balancers-tcp-ports

Point nr 7 reads:

```
Open your preferred web browser to access your app. Example: https://<ibmdomain>:<ingressPort>/
```

If this case the service it's probably not HTTP or HTTPS, so maybe it would be fitting to use an example without HTTP/HTTPS.

One could suggest using `curl` or `telnet` to test.

**Comment by Rachael-Graham** [comment]
Oh great point. I have updated the upstream docs and this change will go out with the next production push! :)
