### ISSUE TITLE
Missing namespace?

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Bluemix-Docs/containers#2281]
In this page, https://console.bluemix.net/docs/containers/cs_dedicated_tokens.html, I think the last command `kubectl apply -f mypod.yaml` is missing the namespace, which must be the same entered in the previous step where the secret is created:

`kubectl --namespace <kubernetes_namespace> create secret docker-registry <secret_name>  --docker-server=<registry_url> --docker-username=token --docker-password=<token_value> --docker-email=<docker_email>`

**Comment by Rachael-Graham** [comment]
Updated: https://console.bluemix.net/docs/containers/cs_dedicated_tokens.html
