### ISSUE TITLE
Remove Documentations for Coscale integration

### ISSUE THREAD

**Issue by jmkanz** [IBM-Bluemix-Docs/containers#2313]
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kubernetes-monitoring-integration

Shows that we can integrate to COSCALE which is no longer a service. It was purchased by NewRelic. The old COSCALE links are all dead. 

Lastly,

The logging and monitoring section of this page:
https://console.bluemix.net/docs/containers/cs_integrations.html#integrations

Will also need changed. Either COSCALE needs removed or NewRelic needs added.

**Comment by artberger** [comment]
Thanks! We've updated the links to the New Relic docs and will keep monitoring this integration area for future changes. Going to close this here.
