### ISSUE TITLE
Unclear command in containers/cs_annotations.md

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix-Docs/containers#2341]
In this section `To create a mutual authentication secret:`, it is unclear what are example.org.csr and `example.org.crt`

**Comment by Rachael-Graham** [comment]
Hey @huikang - We've decided to remove these steps entirely, as there's several different ways to create a self-signed cert for testing purposes. Going to direct users to https://blog.codeship.com/how-to-set-up-mutual-tls-authentication/ (to create your own CA) or https://www.akadia.com/services/ssh_test_certificate.html (w/o creating your own CA) for steps. This change will go out with the next production push.
