### ISSUE TITLE
Issue with access to repo mentioned in containers/cs_storage_utilities.md

### ISSUE THREAD

**Issue by olivermdelgado** [IBM-Bluemix-Docs/containers#2344]
In step 2 of the 'Automatically provisioning unformatted block storage and authorizing your worker nodes to access the storage` section, you mention cloning a specific repo without mention of how to get access to that repo. Running the command yielded the following for me

```oliver-delgado:pw oliver.delgadoibm.com$ git clone git@github.com:IBM/ibmcloud-storage-utilities.git
Cloning into 'ibmcloud-storage-utilities'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
oliver-delgado:pw oliver.delgadoibm.com$ 
```

Alternatively, if I clone through https (`git clone https://github.com/IBM/ibmcloud-storage-utilities.git`) then it works fine.

**Comment by Nadine2016** [comment]
@olivermdelgado thanks so much. You are absolutely right. I just fixed it and it will be pushed to prod in a couple of minutes. let me know if you find anything else. thanks!!
