### ISSUE TITLE
Broken link in Hybrid cloud topic

### ISSUE THREAD

**Issue by cdmauney** [IBM-Bluemix-Docs/containers#2346]
The link to the blog in the short description is broken. https://cloud.ibm.com/docs/containers/cs_hybrid.html#hybrid_iks_icp

![image](https://user-images.githubusercontent.com/22623884/51946419-10560080-23e7-11e9-9b2c-e872b81f2972.png)

**Comment by cdmauney** [comment]
@artberger It's redirecting me to https://www.ibm.com/developerworks/community/blogs/5092bd93-e659-4f89-8de2-a7ac980487f0/entry/Hybrid_Enhancements_Across_IBM_Cloud_Private_and_IBM_Public_Cloud?lang=en.

**Comment by Rachael-Graham** [comment]
redirect is working; closing
