### ISSUE TITLE
Fix the worker number in the diagram Available hardware for worker nodes

### ISSUE THREAD

**Issue by lionelmace** [IBM-Bluemix-Docs/containers#2373]
On the page https://cloud.ibm.com/docs/containers?topic=containers-plan_clusters#shared_dedicated_node

![image](https://user-images.githubusercontent.com/12241613/54614530-da371380-4a5c-11e9-9e05-ed7ba7699cf4.png)

the schema `Available hardware for worker nodes` mentioned `Worker Node 1` twice. It should be Worker Node 1 and Worker Node 2.

**Comment by Rachael-Graham** [comment]
Thanks!! Changed & going out in production today.
