### ISSUE TITLE
In StatefulSet paragraph the line about databases should read "stateful"

### ISSUE THREAD

**Issue by SteveKimmel** [IBM-Bluemix-Docs/containers#2380]
Hi,
  In the StatefulSet description the line that reads: "However, some apps, such as databases, must be stateless." should probably be changed to read "However, some apps, such as databases, maintain state" or something like that.

**Comment by artberger** [comment]
Thanks for catching this! I've updated our source repo, and it will go out with our next prod push. I'm going to close this, but let us know if you have any other questions/feedback.
