### ISSUE TITLE
Use ksvc instead of svc

### ISSUE THREAD

**Issue by andrewyuau** [IBM-Bluemix-Docs/containers#2382]
In the Knative tutorial at https://cloud.ibm.com/docs/containers?topic=containers-knative_tutorial#knative_tutorial , step 4 of lesson 2 shows `kubectl get svc/kn-helloworld`, but the resulting output is not useful.

The example output shows the right output from `kubectl get ksvc`. Should step 4 be showing `kubectl get ksvc`?

**Comment by Nadine2016** [comment]
@andrewyuau thanks for your comment on the tutorial. We updated the tutorial to use `kubectl get ksvc` and it will go out with our next prod push. Thanks.
