### ISSUE TITLE
Firewall rules do not include details about IBM File storage options

### ISSUE THREAD

**Issue by mbirch-ca** [IBM-Bluemix-Docs/containers#2397]
When looking at the details to determine what [firewall rules needed IKS](https://cloud.ibm.com/docs/containers?topic=containers-firewall#firewall), there is no reference on the required configuration for the storage options provided by IBM Cloud.

This includes options under Persistent Storage including

- [IBM File Storage for IBM Cloud](https://cloud.ibm.com/docs/containers?topic=containers-file_storage#file_storage)
- [IBM File Storage for IBM Cloud](https://cloud.ibm.com/docs/containers?topic=containers-block_storage#block_storage)
- [IBM Cloud Object Storage](https://cloud.ibm.com/docs/containers?topic=containers-object_storage#object_storage)

Without the details, its possible someone might see an error like 

> mount.nfs: Connection timed out

This would likely meaning providing details about the subnet range to add into a Calico policy.

**Comment by mbirch-ca** [comment]
To provide an example, when I use File Storage it appears to resolve to an internal IP address (10.x.x.x) and given how Calico policies work, I need to be able to provide the IP address that applies.

The closest information I have found was this list of the [infrastructure service network](https://cloud.ibm.com/docs/infrastructure/hardware-firewall-dedicated?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges#service-network-on-backend-private-network-) but allowing access to 4096 ip addresses might not be seen as following "deny all, permit by exception" to access a storage device

**Comment by Nadine2016** [comment]
closing here as we will continue tracking this issue in https://github.ibm.com/alchemy-containers/armada-storage/issues/943

@mbirch-ca fyi
