### ISSUE TITLE
Deprecated CLI Arguments Used in Documentation

### ISSUE THREAD

**Issue by danchirillo** [IBM-Bluemix-Docs/containers#2399]
The command line arguments at [Setting up the API key to enable access to the infrastructure portfolio](https://cloud.ibm.com/docs/containers?topic=containers-users#api_key) are no longer valid for the current release (as of today) of ibmcloud CLI (version 0.15.1+d1a593d-2019-04-11T08:00:31+00:00).

**Comment by Rachael-Graham** [comment]
@danchirillo Which arguments?

**Comment by danchirillo** [comment]
Hi @Rachael-Graham 

I had an issue with the ks argument.   Just a bit of history before I get into details.  I don't know which version I was running prior to today, but at the command line today I was prompted to upgrade ibmcloud CLI:

![image](https://user-images.githubusercontent.com/12007310/56818337-6e8f5580-6815-11e9-8a5c-df14a6484e49.png)


I then ran into an aside with the ks argument.  Here is the complaint.  Note that ks is not in the list of valid commands:
![image](https://user-images.githubusercontent.com/12007310/56817729-1f94f080-6814-11e9-9a32-70278acef458.png)

In the same shell, I later ran curl -sL https://ibm.biz/idt-installer | bash per the instructions for setting up a Kubernetes cluster:
![image](https://user-images.githubusercontent.com/12007310/56817888-739fd500-6814-11e9-9d10-3df1f1855139.png)

Now, in the same shell, ks is a valid argument:
![image](https://user-images.githubusercontent.com/12007310/56817927-8e724980-6814-11e9-989e-1d81e114f816.png)

Might it be the case that installing the ibmcloud command CLI does not by default add the Kubernetes support?

**Comment by Rachael-Graham** [comment]
Yes, I think you have it right--When you install the `ibmcloud` CLI by itself, you have to then also manually install the `ks` plugin for it by running `ibmcloud plugin install kubernetes-service`. However, if you use that installer script, then the plugin is installed automatically.

BUT that being said, you're also correct in that updating your `ibmcloud` cli should definitely not uninstall your `ks` plugin. I'll investigate with the core `ibmcloud` CLI team.

**Comment by danchirillo** [comment]
That explains it, then. I had not installed the Kubernetes plugin prior to the upgrade, which makes this  an operator error issue ;)

**Comment by Rachael-Graham** [comment]
Ohh okay makes sense! Closing this issue then. 🎉
