### ISSUE TITLE
Put time estimate on top of page (how long to read/perform steps)

### ISSUE THREAD

**Issue by RogerSnook** [IBM-Bluemix-Docs/containers#2419]
A nice best practice from the https://istio.io/docs/concepts/traffic-management/ site - at the top of each page it tells you how long it would take to READ or perform the steps.  Can we consider this for the future?  (I'm also pinging the platform team to see if this could be a platform wide update).

**Comment by RogerSnook** [comment]
Mark Meredith is referring this to @jenschlot for review on ALL docs pages. (This is REALLY useful for TRAINING purposes!).

**Comment by Nadine2016** [comment]
closing here because this is a general requirement that affects all of IBM Cloud docs and Jenifer Schlotfeldt is the right person who can address this. I opened an issue for them here: https://github.ibm.com/Bluemix/Documentation-content/issues/5284 closing
