### ISSUE TITLE
volumeMount names are wrong in example yaml

### ISSUE THREAD

**Issue by cin** [IBM-Bluemix-Docs/containers#2430]
The volumeMounts are wrong in the "Example stateful set with anti-affinity rule and delayed block storage creation:". `www` and `wwww` should be `myvol1` and `myvol2` respectively.

Thanks for the example btw. Still debugging why my statefulset isn't working, but this is helping debug it at least. :)

**Comment by artberger** [comment]
@cin thanks for opening the issue! I've addressed it in our source repo, and it will go out with our next prod push, so I'm going to close this here.

Also if you're still having problems you can also always try posting in our Slack user channels, [internal](https://ibm-argonauts.slack.com/messages/C4S4NUCB1) or [external](https://ibm-container-service.slack.com/messages/C4G6362ER).
