### ISSUE TITLE
All images hyperlink are broken in the page Planning clusters and apps

### ISSUE THREAD

**Issue by lionelmace** [IBM-Bluemix-Docs/containers#671]
All the images on the page below are hyperlink to open the image, but if you click on any image you get the error message: "Sorry, this content isn’t available."
https://console.bluemix.net/docs/containers/cs_planning.html#cs_planning_apps_storage

Two options to resolve this issue:
1. We remove the hyperlink on each image
2. We fix the link on each image to open the image in a new page

@kKronstainBrown

**Comment by kKronstainBrown** [comment]
@lionelmace Thanks for reporting this! I'm seeing the behavior you're describing in Chrome and Safari, but in Firefox the images download. Is that consistent with what you were seeing?

**Comment by kKronstainBrown** [comment]
@lionelmace Since there's no good workarounds, we removed the links around the images. Thanks for the notice on this! Please continue opening issues for us in the future.
